export const FETCH_CARS_REQUEST = "FETCH_CARS_REQUEST";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
export const FETCH_CARS_ERROR = "FETCH_CARS_ERROR";
export const SORT_APHABETICALLY = "SORT_APHABETICALLY";
export const SORT_BY_AVAILABILITY = "SORT_BY_AVAILABILITY";
export const SORT_DEFAULT = "SORT_DEFAULT";
